<!-- -- bloc nav -- -->
<nav>
    <!-- formation -->
    <a href="#formation">Formation</a>
    <!-- Compétences -->
    <a href="#competences">Compétences</a>
    <!-- Visualisation du CV -->
    <a href="#viewCV">Visualiser mon CV</a>
    <!-- téléchargement cv -->
    <a href="#DownloadCV">Télécharger mon CV</a>
    <!-- Contact -->
    <a href="#contact">Contact</a>
</nav>

<!-- -- div réseaux -- -->
<div>
    <!-- Linkedin -->
    <a href="">Linkedin</a>
    <!-- Github -->
    <a href="">Github</a>
</div>