<div>
    <canvas id="canvas-home"></canvas>
    <h1 class="main-title gradient-text">Coralie Girardi</h1>
    <p class="gradient-text">Développeuse web</p>
</div>
<h2>Qui je suis?</h2>
<p>Je suis une developpeuse web Fullstack de 22 ans originaire de Marseille, Dipômée récemment de la 3W Academy. </p>
<h2>Formations</h2>
<h3>RNCP5 Développement web Fullstack <span class="italic">OBTENU</span></h3>
<ul>
    <li>Front-end:</li>
    <ul>
        <li>HTML</li>
        <li>CSS</li>
        <li>Javascript</li>
    </ul>
    <li>Back-end:</li>
    <ul>
        <li>PHP</li>
        <li>SQL</li>
        <li>Python</li>
    </ul>
    <li>Compétences transverses</li>
    <ul>
        <li>Symfony</li>
        <li>Cadre MVC</li>
        <li>Bootstrap</li>
        <li>PhPMyAdmin</li>
        <li>CMS (Wordpress)</li>
        <li>JQuery</li>
        <li>API</li>
    </ul>
</ul>
<h3>TOSA Python <span class="italic">OBTENU(niveau initial)</span></h3>
<ul>
    <li>TKinter</li>
    <li>SQLite</li>
    <li>Python</li>
</ul>
<h3>Autodidacte</h3>
<ul></ul>