<div class="large-header">
    <canvas id="canvas-home"></canvas>
    <h1 class="main-title gradient-text">Coralie Girardi</h1>
    <p class="gradient-text">Développeuse web</p>
</div>
<h2>Mon profil</h2>
<p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos, perferendis magnam. Sed eos aut molestiae id vitae,
    similique natus, cum quae inventore incidunt facere. Quaerat, esse corrupti inventore aliquid voluptate optio et
    perferendis fugiat rem praesentium, doloribus vel illum rerum sapiente itaque laudantium nobis harum voluptas.
    Dolorem dicta aspernatur qui.</p>
<h2>Formations</h2>
<h3>RNCP5 Développement web fullstack</h3>
<ul>
    <li>Front-end:</li>
    <ul>
        <li>HTML</li>
        <li>CSS</li>
        <li>Javascript</li>
    </ul>
    <li>Back-end:</li>
    <ul>
        <li>PHP</li>
        <li>SQL</li>
    </ul>
    <li>Compétences transverses</li>
    <ul>
        <li>Symfony</li>
        <li>Cadre MVC</li>
        <li>Bootstrap</li>
        <li>PhPMyAdmin</li>
        <li>CMS (Wordpress)</li>
        <li>JQuery</li>
        <li>API</li>
    </ul>

</ul>