<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coralie Girardi</title>
    <meta name="description" content="Portfolio de Coralie Girardi,Développeuse web">
    <link rel="stylesheet" href="css/style.css">
    <script src="https://kit.fontawesome.com/fe7cbf9353.js" crossorigin="anonymous"></script>

</head>

<body>
    <!-- INCLUDE DU HEADER -->
    <header>
        <?php include_once '_header.phtml'; ?>
    </header>
    <!-- INCLUDE DU TEMPLATE -->
    <main>
        <?php include $template; ?>
    </main>
    <!-- INCLUDE FOOTER  -->
    <footer>
        <?php include_once '_footer.phtml'; ?>
    </footer>
</body>

</html>